"""empty message

Revision ID: 35213fe5b24a
Revises: ea33e1cc193b
Create Date: 2023-07-25 08:56:21.753282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35213fe5b24a'
down_revision = 'ea33e1cc193b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('posted', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_column('posted')

    # ### end Alembic commands ###
